/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-15 at 08:27:03 UTC 
 * Modify at your own risk.
 */

package cod.com.appspot.endpoints_final.testGCS;

/**
 * Service definition for TestGCS (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link TestGCSRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class TestGCS extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.19.1 of the testGCS library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://endpoints-final.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "testGCS/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public TestGCS(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  TestGCS(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Delete collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code TestGCS testGCS = new TestGCS(...);}
   *   {@code TestGCS.Delete.List request = testGCS.delete().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Delete delete() {
    return new Delete();
  }

  /**
   * The "delete" collection of methods.
   */
  public class Delete {

    /**
     * Create a request for the method "delete.deletephoto".
     *
     * This request holds the parameters needed by the testGCS server.  After setting any optional
     * parameters, call the {@link Deletephoto#execute()} method to invoke the remote operation.
     *
     * @param filename
     * @param isNdbEntry
     * @return the request
     */
    public Deletephoto deletephoto(java.lang.String filename, java.lang.Boolean isNdbEntry) throws java.io.IOException {
      Deletephoto result = new Deletephoto(filename, isNdbEntry);
      initialize(result);
      return result;
    }

    public class Deletephoto extends TestGCSRequest<cod.com.appspot.endpoints_final.testGCS.model.MainDeleteResponseMessage> {

      private static final String REST_PATH = "delete";

      /**
       * Create a request for the method "delete.deletephoto".
       *
       * This request holds the parameters needed by the the testGCS server.  After setting any optional
       * parameters, call the {@link Deletephoto#execute()} method to invoke the remote operation. <p>
       * {@link
       * Deletephoto#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param filename
       * @param isNdbEntry
       * @since 1.13
       */
      protected Deletephoto(java.lang.String filename, java.lang.Boolean isNdbEntry) {
        super(TestGCS.this, "GET", REST_PATH, null, cod.com.appspot.endpoints_final.testGCS.model.MainDeleteResponseMessage.class);
        this.filename = com.google.api.client.util.Preconditions.checkNotNull(filename, "Required parameter filename must be specified.");
        this.isNdbEntry = com.google.api.client.util.Preconditions.checkNotNull(isNdbEntry, "Required parameter isNdbEntry must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Deletephoto setAlt(java.lang.String alt) {
        return (Deletephoto) super.setAlt(alt);
      }

      @Override
      public Deletephoto setFields(java.lang.String fields) {
        return (Deletephoto) super.setFields(fields);
      }

      @Override
      public Deletephoto setKey(java.lang.String key) {
        return (Deletephoto) super.setKey(key);
      }

      @Override
      public Deletephoto setOauthToken(java.lang.String oauthToken) {
        return (Deletephoto) super.setOauthToken(oauthToken);
      }

      @Override
      public Deletephoto setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Deletephoto) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Deletephoto setQuotaUser(java.lang.String quotaUser) {
        return (Deletephoto) super.setQuotaUser(quotaUser);
      }

      @Override
      public Deletephoto setUserIp(java.lang.String userIp) {
        return (Deletephoto) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String filename;

      /**

       */
      public java.lang.String getFilename() {
        return filename;
      }

      public Deletephoto setFilename(java.lang.String filename) {
        this.filename = filename;
        return this;
      }

      @com.google.api.client.util.Key("is_ndb_entry")
      private java.lang.Boolean isNdbEntry;

      /**

       */
      public java.lang.Boolean getIsNdbEntry() {
        return isNdbEntry;
      }

      public Deletephoto setIsNdbEntry(java.lang.Boolean isNdbEntry) {
        this.isNdbEntry = isNdbEntry;
        return this;
      }

      @Override
      public Deletephoto set(String parameterName, Object value) {
        return (Deletephoto) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Display collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code TestGCS testGCS = new TestGCS(...);}
   *   {@code TestGCS.Display.List request = testGCS.display().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Display display() {
    return new Display();
  }

  /**
   * The "display" collection of methods.
   */
  public class Display {

    /**
     * Create a request for the method "display.getphotos".
     *
     * This request holds the parameters needed by the testGCS server.  After setting any optional
     * parameters, call the {@link Getphotos#execute()} method to invoke the remote operation.
     *
     * @param fetch
     * @return the request
     */
    public Getphotos getphotos(java.lang.Long fetch) throws java.io.IOException {
      Getphotos result = new Getphotos(fetch);
      initialize(result);
      return result;
    }

    public class Getphotos extends TestGCSRequest<cod.com.appspot.endpoints_final.testGCS.model.MainDownloadResponseCollection> {

      private static final String REST_PATH = "display";

      /**
       * Create a request for the method "display.getphotos".
       *
       * This request holds the parameters needed by the the testGCS server.  After setting any optional
       * parameters, call the {@link Getphotos#execute()} method to invoke the remote operation. <p>
       * {@link
       * Getphotos#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param fetch
       * @since 1.13
       */
      protected Getphotos(java.lang.Long fetch) {
        super(TestGCS.this, "GET", REST_PATH, null, cod.com.appspot.endpoints_final.testGCS.model.MainDownloadResponseCollection.class);
        this.fetch = com.google.api.client.util.Preconditions.checkNotNull(fetch, "Required parameter fetch must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Getphotos setAlt(java.lang.String alt) {
        return (Getphotos) super.setAlt(alt);
      }

      @Override
      public Getphotos setFields(java.lang.String fields) {
        return (Getphotos) super.setFields(fields);
      }

      @Override
      public Getphotos setKey(java.lang.String key) {
        return (Getphotos) super.setKey(key);
      }

      @Override
      public Getphotos setOauthToken(java.lang.String oauthToken) {
        return (Getphotos) super.setOauthToken(oauthToken);
      }

      @Override
      public Getphotos setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Getphotos) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Getphotos setQuotaUser(java.lang.String quotaUser) {
        return (Getphotos) super.setQuotaUser(quotaUser);
      }

      @Override
      public Getphotos setUserIp(java.lang.String userIp) {
        return (Getphotos) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long fetch;

      /**

       */
      public java.lang.Long getFetch() {
        return fetch;
      }

      public Getphotos setFetch(java.lang.Long fetch) {
        this.fetch = fetch;
        return this;
      }

      @com.google.api.client.util.Key("date_time")
      private java.lang.String dateTime;

      /**

       */
      public java.lang.String getDateTime() {
        return dateTime;
      }

      public Getphotos setDateTime(java.lang.String dateTime) {
        this.dateTime = dateTime;
        return this;
      }

      @Override
      public Getphotos set(String parameterName, Object value) {
        return (Getphotos) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Upload collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code TestGCS testGCS = new TestGCS(...);}
   *   {@code TestGCS.Upload.List request = testGCS.upload().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Upload upload() {
    return new Upload();
  }

  /**
   * The "upload" collection of methods.
   */
  public class Upload {

    /**
     * Create a request for the method "upload.putphoto".
     *
     * This request holds the parameters needed by the testGCS server.  After setting any optional
     * parameters, call the {@link Putphoto#execute()} method to invoke the remote operation.
     *
     * @param content the {@link cod.com.appspot.endpoints_final.testGCS.model.MainUploadRequestMessage}
     * @return the request
     */
    public Putphoto putphoto(cod.com.appspot.endpoints_final.testGCS.model.MainUploadRequestMessage content) throws java.io.IOException {
      Putphoto result = new Putphoto(content);
      initialize(result);
      return result;
    }

    public class Putphoto extends TestGCSRequest<Void> {

      private static final String REST_PATH = "upload";

      /**
       * Create a request for the method "upload.putphoto".
       *
       * This request holds the parameters needed by the the testGCS server.  After setting any optional
       * parameters, call the {@link Putphoto#execute()} method to invoke the remote operation. <p>
       * {@link
       * Putphoto#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link cod.com.appspot.endpoints_final.testGCS.model.MainUploadRequestMessage}
       * @since 1.13
       */
      protected Putphoto(cod.com.appspot.endpoints_final.testGCS.model.MainUploadRequestMessage content) {
        super(TestGCS.this, "POST", REST_PATH, content, Void.class);
      }

      @Override
      public Putphoto setAlt(java.lang.String alt) {
        return (Putphoto) super.setAlt(alt);
      }

      @Override
      public Putphoto setFields(java.lang.String fields) {
        return (Putphoto) super.setFields(fields);
      }

      @Override
      public Putphoto setKey(java.lang.String key) {
        return (Putphoto) super.setKey(key);
      }

      @Override
      public Putphoto setOauthToken(java.lang.String oauthToken) {
        return (Putphoto) super.setOauthToken(oauthToken);
      }

      @Override
      public Putphoto setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Putphoto) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Putphoto setQuotaUser(java.lang.String quotaUser) {
        return (Putphoto) super.setQuotaUser(quotaUser);
      }

      @Override
      public Putphoto setUserIp(java.lang.String userIp) {
        return (Putphoto) super.setUserIp(userIp);
      }

      @Override
      public Putphoto set(String parameterName, Object value) {
        return (Putphoto) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link TestGCS}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link TestGCS}. */
    @Override
    public TestGCS build() {
      return new TestGCS(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link TestGCSRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setTestGCSRequestInitializer(
        TestGCSRequestInitializer testgcsRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(testgcsRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
