/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-15 at 08:27:03 UTC 
 * Modify at your own risk.
 */

package cod.com.appspot.endpoints_final.testGCS.model;

/**
 * Model definition for MainDownloadResponseMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the testGCS. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainDownloadResponseMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("date_time")
  private java.lang.String dateTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String filename;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String photo;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDateTime() {
    return dateTime;
  }

  /**
   * @param dateTime dateTime or {@code null} for none
   */
  public MainDownloadResponseMessage setDateTime(java.lang.String dateTime) {
    this.dateTime = dateTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFilename() {
    return filename;
  }

  /**
   * @param filename filename or {@code null} for none
   */
  public MainDownloadResponseMessage setFilename(java.lang.String filename) {
    this.filename = filename;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPhoto() {
    return photo;
  }

  /**
   * @param photo photo or {@code null} for none
   */
  public MainDownloadResponseMessage setPhoto(java.lang.String photo) {
    this.photo = photo;
    return this;
  }

  @Override
  public MainDownloadResponseMessage set(String fieldName, Object value) {
    return (MainDownloadResponseMessage) super.set(fieldName, value);
  }

  @Override
  public MainDownloadResponseMessage clone() {
    return (MainDownloadResponseMessage) super.clone();
  }

}
