/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-24 at 14:46:21 UTC 
 * Modify at your own risk.
 */

package cod.com.appspot.omega_terrain_803.testGCS.model;

import cod.com.appspot.omega_terrain_803.testGCS.model.MainDownloadResponseMessage;

/**
 * Model definition for MainDownloadResponseCollection.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the testGCS. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainDownloadResponseCollection extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<MainDownloadResponseMessage> photos;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<MainDownloadResponseMessage> getPhotos() {
    return photos;
  }

  /**
   * @param photos photos or {@code null} for none
   */
  public MainDownloadResponseCollection setPhotos(java.util.List<MainDownloadResponseMessage> photos) {
    this.photos = photos;
    return this;
  }

  @Override
  public MainDownloadResponseCollection set(String fieldName, Object value) {
    return (MainDownloadResponseCollection) super.set(fieldName, value);
  }

  @Override
  public MainDownloadResponseCollection clone() {
    return (MainDownloadResponseCollection) super.clone();
  }

}
