/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-12 at 22:24:30 UTC 
 * Modify at your own risk.
 */

package cod.com.appspot.art_everywhere.artEverywhere.model;

/**
 * Model definition for MainArtistDetailsMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the artEverywhere. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MainArtistDetailsMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String bio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cognome;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String message;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nickname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nome;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pic;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sito;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBio() {
    return bio;
  }

  /**
   * @param bio bio or {@code null} for none
   */
  public MainArtistDetailsMessage setBio(java.lang.String bio) {
    this.bio = bio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCognome() {
    return cognome;
  }

  /**
   * @param cognome cognome or {@code null} for none
   */
  public MainArtistDetailsMessage setCognome(java.lang.String cognome) {
    this.cognome = cognome;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public MainArtistDetailsMessage setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMessage() {
    return message;
  }

  /**
   * @param message message or {@code null} for none
   */
  public MainArtistDetailsMessage setMessage(java.lang.String message) {
    this.message = message;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNickname() {
    return nickname;
  }

  /**
   * @param nickname nickname or {@code null} for none
   */
  public MainArtistDetailsMessage setNickname(java.lang.String nickname) {
    this.nickname = nickname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNome() {
    return nome;
  }

  /**
   * @param nome nome or {@code null} for none
   */
  public MainArtistDetailsMessage setNome(java.lang.String nome) {
    this.nome = nome;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPic() {
    return pic;
  }

  /**
   * @param pic pic or {@code null} for none
   */
  public MainArtistDetailsMessage setPic(java.lang.String pic) {
    this.pic = pic;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSito() {
    return sito;
  }

  /**
   * @param sito sito or {@code null} for none
   */
  public MainArtistDetailsMessage setSito(java.lang.String sito) {
    this.sito = sito;
    return this;
  }

  @Override
  public MainArtistDetailsMessage set(String fieldName, Object value) {
    return (MainArtistDetailsMessage) super.set(fieldName, value);
  }

  @Override
  public MainArtistDetailsMessage clone() {
    return (MainArtistDetailsMessage) super.clone();
  }

}
